-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Tempo de geração: 12/11/2025 às 15:05
-- Versão do servidor: 8.2.0
-- Versão do PHP: 8.2.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `u697465806_movhealth`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `planos_treino_gerados`
--

DROP TABLE IF EXISTS `planos_treino_gerados`;
CREATE TABLE IF NOT EXISTS `planos_treino_gerados` (
  `id` int NOT NULL AUTO_INCREMENT,
  `usuario_id` int NOT NULL,
  `profissional_id` int DEFAULT NULL,
  `anamnese_id` int NOT NULL,
  `data_criacao_plano` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `bibliografia_plano` text COLLATE utf8mb4_unicode_ci,
  `foco_primario` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `duracao_treino_geral` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dias_plano` int DEFAULT '5' COMMENT 'Duração do plano em dias',
  `equipamento_geral` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_planos_usuario` (`usuario_id`),
  KEY `idx_planos_profissional` (`profissional_id`),
  KEY `idx_planos_anamnese` (`anamnese_id`)
) ENGINE=InnoDB AUTO_INCREMENT=116 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Despejando dados para a tabela `planos_treino_gerados`
--

INSERT INTO `planos_treino_gerados` (`id`, `usuario_id`, `profissional_id`, `anamnese_id`, `data_criacao_plano`, `bibliografia_plano`, `foco_primario`, `duracao_treino_geral`, `dias_plano`, `equipamento_geral`) VALUES
(21, 10, 5, 6, '2025-07-02 14:48:08', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- International Diabetes Federation. Global Guidelines for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/128-idf-guidelines-for-type-2-diabetes\n- Sociedade Brasileira de Diabetes. Diretrizes 2023-2024 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2023-2024.pdf', NULL, '45 minutos', 5, NULL),
(22, 23, 5, 12, '2025-07-03 00:16:19', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- International Diabetes Federation. Global Guidelines for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/128-idf-guidelines-for-type-2-diabetes\n- Sociedade Brasileira de Diabetes. Diretrizes 2023-2024 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2023-2024.pdf', 'weight-loss', '45 minutos', 5, NULL),
(23, 2, 5, 2, '2025-07-03 01:01:12', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- Sociedade Brasileira de Diabetes - Diretrizes - https://www.diabetes.org.br/publico/diretrizes-e-posicionamentos-oficiais/diretrizes-da-sociedade-brasileira-de-diabetes\n- IDF Diabetes Atlas - https://diabetesatlas.org/', 'weight-loss', '60 minutos', 5, NULL),
(24, 12, 5, 8, '2025-07-03 01:09:12', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- Sociedade Brasileira de Diabetes. Diretrizes da Sociedade Brasileira de Diabetes 2022-2023 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2022-2023.pdf', NULL, '60 minutos', 5, NULL),
(25, 30, 15, 17, '2025-07-11 14:54:11', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- Sociedade Brasileira de Diabetes. Diretrizes - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-COMPLETA-2019-2020.pdf\n- International Diabetes Federation. Recommendations for Managing Type 2 Diabetes in Primary Care - https://www.idf.org/e-library/guidelines/128-idf-clinical-practice-recommendations-for-managing-type-2-diabetes-in-primary-care.html', 'weight-loss', '60 minutos', 5, NULL),
(26, 30, 15, 17, '2025-07-11 15:27:42', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- IDF Clinical Practice Recommendations for managing Type 2 Diabetes in Primary Care - https://www.idf.org/our-activities/care-prevention/type-2-diabetes.html\n- Sociedade Brasileira de Diabetes. Diretrizes 2022-2023 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-COMPLETA-2023.pdf', 'hypertrophy', '80 minutos', 5, NULL),
(27, 31, 15, 18, '2025-07-19 17:03:51', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html\n- Sociedade Brasileira de Diabetes. Diretrizes - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-COMPLETA-2020.pdf', 'weight-loss', '60 minutos', 5, NULL),
(28, 32, 15, 19, '2025-07-20 00:20:06', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- International Diabetes Federation. IDF Diabetes Atlas, 9th edition - https://www.diabetesatlas.org', 'functional-strength', '60 minutos', 5, NULL),
(29, 33, 15, 20, '2025-07-20 00:54:52', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- IDF Diabetes Atlas, 10th Edition - https://diabetesatlas.org/\n- Sociedade Brasileira de Diabetes - Diretrizes 2022-2023 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2022-2023.pdf', 'aerobic-resistance', '60 minutos', 5, NULL),
(30, 33, 15, 20, '2025-07-20 00:56:31', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- IDF Diabetes Atlas, 10th Edition - https://diabetesatlas.org/\n- Sociedade Brasileira de Diabetes - Diretrizes 2022-2023 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2022-2023.pdf', 'aerobic-resistance', '60 minutos', 5, NULL),
(31, 34, 15, 21, '2025-07-20 01:12:04', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes. Diretrizes - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-COMPLETA-2020.pdf', 'aerobic-resistance', '90 minutos', 5, NULL),
(32, 35, 15, 22, '2025-07-20 01:47:40', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- IDF Clinical Practice Recommendations for Managing Type 2 Diabetes in Primary Care - https://www.idf.org/e-library/guidelines/128-idf-clinical-practice-recommendations-for-managing-type-2-diabetes-in-primary-care.html\n- Sociedade Brasileira de Diabetes - Diretrizes 2023 - https://www.diabetes.org.br/publico/diretrizes\n- PubMed - https://pubmed.ncbi.nlm.nih.gov/', 'aerobic-resistance', '100 minutos', 5, NULL),
(34, 38, 15, 24, '2025-07-21 22:51:18', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- Sociedade Brasileira de Diabetes. Diretrizes - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2022-2023.pdf\n- International Diabetes Federation. Diabetes Atlas - https://idf.org/e-library/epidemiology-research/diabetes-atlas.html', 'hypertrophy', '75 minutos', 5, NULL),
(35, 38, 15, 24, '2025-07-21 23:16:05', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes. Diretrizes 2023 - https://www.diabetes.org.br/profissionais/images/pdf/DIRETRIZES-SBD-2023.pdf', 'hypertrophy', '75 minutos', 5, NULL),
(36, 39, 15, 25, '2025-07-22 02:09:42', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- IDF Clinical Practice Recommendations for managing Type 2 Diabetes in Primary Care - https://idf.org/e-library/guidelines/81-idf-clinical-practice-recommendations-for-managing-type-2-diabetes-in-primary-care.html\n- Sociedade Brasileira de Diabetes. Diretrizes 2022-2023 - https://www.diabetes.org.br/profissionais/images/diretrizes-sbd-2022-2023.pdf', 'weight-loss', '90 minutos', 5, NULL),
(37, 39, 15, 25, '2025-07-22 14:51:21', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html\n- Diretrizes da Sociedade Brasileira de Diabetes 2019-2020 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-COMPLETA-2019-2020.pdf', 'weight-loss', '90 minutos', 5, NULL),
(38, 41, 15, 27, '2025-07-23 01:02:08', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- IDF Diabetes Atlas, 10th Edition - https://diabetesatlas.org/', 'weight-loss', '60 minutos', 5, NULL),
(39, 41, 15, 27, '2025-07-23 01:02:20', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- IDF Diabetes Atlas, 10th Edition - https://diabetesatlas.org/', 'weight-loss', '60 minutos', 5, NULL),
(40, 40, 15, 26, '2025-07-23 01:09:50', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html\n- Sociedade Brasileira de Diabetes. Diretrizes da Sociedade Brasileira de Diabetes 2019-2020 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-COMPLETA-2019-2020.pdf', 'weight-loss', '70 minutos', 5, NULL),
(41, 43, 15, 28, '2025-07-23 23:15:10', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 10th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2023 - https://diabetesjournals.org/care/issue/46/Supplement_1\n- International Diabetes Federation. Clinical practice recommendations for managing Type 2 Diabetes in Primary Care - https://www.idf.org', 'weight-loss', '90 minutos', 5, NULL),
(42, 43, 15, 28, '2025-07-24 22:12:20', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation - https://www.idf.org/', 'weight-loss', '75 minutos', 5, NULL),
(43, 43, 15, 28, '2025-07-24 22:12:30', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation - https://www.idf.org/', 'weight-loss', '75 minutos', 5, NULL),
(45, 37, 15, 23, '2025-07-24 22:26:30', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '75 minutos', 5, NULL),
(46, 38, 15, 24, '2025-07-24 22:36:13', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes. Diretrizes da Sociedade Brasileira de Diabetes 2019-2020 - https://www.diabetes.org.br/publico/diretrizes-sbd', 'hypertrophy', '75 minutos', 5, NULL),
(47, 35, 15, 22, '2025-07-24 22:42:15', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'aerobic-resistance', '75 minutos', 5, NULL),
(48, 40, 15, 26, '2025-07-24 22:45:20', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- International Diabetes Federation. Diabetes and Physical Activity - https://www.idf.org/our-activities/care-prevention/physical-activity.html\n- Sociedade Brasileira de Diabetes. Diretrizes 2023-2024 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2023-2024.pdf\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- PubMed - Physical Activity and Diabetes: An Overview - https://pubmed.ncbi.nlm.nih.gov/28973142/', 'weight-loss', '75 minutos', 5, NULL),
(49, 34, 15, 21, '2025-07-24 22:54:23', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'aerobic-resistance', '90 minutos', 5, NULL),
(50, 41, 15, 27, '2025-07-24 22:58:46', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '80 minutos', 5, NULL),
(51, 41, 15, 27, '2025-07-24 23:01:50', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '80 minutos', 5, NULL),
(52, 32, 15, 19, '2025-07-25 02:20:16', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'functional-strength', '70 minutos', 5, NULL),
(53, 43, 15, 28, '2025-07-25 15:09:45', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation - https://www.idf.org/\n- Sociedade Brasileira de Diabetes - https://www.diabetes.org.br/\n- PubMed - https://pubmed.ncbi.nlm.nih.gov/', 'weight-loss', '75 minutos', 5, NULL),
(54, 31, 15, 18, '2025-07-26 01:15:52', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '75 minutos', 5, NULL),
(55, 45, 15, 29, '2025-07-26 22:37:45', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'aerobic-resistance', '80 minutos', 5, NULL),
(56, 45, 15, 29, '2025-07-26 22:41:34', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html', 'aerobic-resistance', '80 minutos', 5, NULL),
(57, 45, 15, 29, '2025-07-26 22:43:53', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Global guidelines for type 2 diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes', 'aerobic-resistance', '75 minutos', 5, NULL),
(58, 37, 15, 23, '2025-07-28 19:43:58', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- International Diabetes Federation - https://www.idf.org/\n- Sociedade Brasileira de Diabetes - https://www.diabetes.org.br/\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '75 minutos', 5, NULL),
(59, 35, 15, 22, '2025-07-29 21:57:00', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes\n- Sociedade Brasileira de Diabetes. Diretrizes da SBD 2023-2024 - https://www.diabetes.org.br/publico/diretrizes-da-sbd', 'aerobic-resistance', '115 minutos', 5, NULL),
(60, 47, 15, 30, '2025-07-30 21:12:01', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Recommendations for Managing Type 2 Diabetes in Adults - https://www.idf.org/e-library/guidelines/87-idf-clinical-practice-recommendations-for-managing-type-2-diabetes-in-primary-care.html\n- Sociedade Brasileira de Diabetes - Diretrizes 2023 - https://www.diabetes.org.br/profissionais/images/docs/Diretrizes_SBD_2023.pdf', 'aerobic-resistance', '70 minutos', 5, NULL),
(61, 47, 15, 30, '2025-07-30 21:19:14', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'aerobic-resistance', '75 minutos', 5, NULL),
(62, 47, 15, 30, '2025-07-31 01:42:12', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'aerobic-resistance', '60 minutos', 5, NULL),
(63, 47, 15, 30, '2025-07-31 01:42:15', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'aerobic-resistance', '60 minutos', 5, NULL),
(64, 12, 5, 16, '2025-07-31 14:13:30', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'endurance', '80 minutos', 5, NULL),
(65, 48, 15, 31, '2025-08-01 20:43:31', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'hypertrophy', '75 minutos', 5, NULL),
(66, 51, NULL, 33, '2025-08-02 15:57:25', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html', 'weight-loss', '65 minutos', 5, NULL),
(67, 58, 15, 35, '2025-08-02 17:53:49', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. IDF Diabetes Atlas, 10th Edition - https://diabetesatlas.org/', 'weight-loss', '70 minutos', 5, NULL),
(68, 59, 15, 36, '2025-08-02 18:42:46', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation - https://www.idf.org/', 'weight-loss', '60 minutos', 5, NULL),
(69, 60, 15, 37, '2025-08-02 18:52:35', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. IDF Diabetes Atlas - https://www.diabetesatlas.org/', 'weight-loss', '75 minutos', 5, NULL),
(70, 61, 15, 38, '2025-08-02 19:21:27', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Diabetes Atlas, 10th Edition - https://diabetesatlas.org/', 'aerobic-resistance', '90 minutos', 5, NULL),
(71, 61, 15, 38, '2025-08-02 19:23:01', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Diabetes Atlas, 10th Edition - https://diabetesatlas.org/', 'aerobic-resistance', '90 minutos', 5, NULL),
(72, 62, 15, 39, '2025-08-02 19:37:50', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '75 minutos', 5, NULL),
(73, 62, 15, 39, '2025-08-02 19:39:46', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '75 minutos', 5, NULL),
(74, 63, 15, 40, '2025-08-02 20:43:24', '==Bibliografia Recomendada==\n- ACSM\'s Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Diabetes Atlas, 10th Edition - https://www.diabetesatlas.org', 'weight-loss', '75 minutos', 5, NULL),
(75, 51, NULL, 33, '2025-08-02 21:51:15', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation (IDF), Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes (SBD) Diretrizes - https://www.diabetes.org.br/publico/diretrizes-sbd', 'weight-loss', '70 minutos', 5, NULL),
(76, 51, NULL, 33, '2025-08-02 21:51:17', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation (IDF), Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes (SBD) Diretrizes - https://www.diabetes.org.br/publico/diretrizes-sbd', 'weight-loss', '70 minutos', 5, NULL),
(77, 51, NULL, 33, '2025-08-02 21:51:18', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation (IDF), Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes (SBD) Diretrizes - https://www.diabetes.org.br/publico/diretrizes-sbd', 'weight-loss', '70 minutos', 5, NULL),
(78, 51, NULL, 33, '2025-08-02 21:51:31', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation (IDF), Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes (SBD) Diretrizes - https://www.diabetes.org.br/publico/diretrizes-sbd', 'weight-loss', '70 minutos', 5, NULL),
(79, 51, NULL, 33, '2025-08-02 21:53:05', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation (IDF), Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes (SBD) Diretrizes - https://www.diabetes.org.br/publico/diretrizes-sbd', 'weight-loss', '70 minutos', 5, NULL),
(80, 51, NULL, 33, '2025-08-02 21:53:06', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation (IDF), Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes (SBD) Diretrizes - https://www.diabetes.org.br/publico/diretrizes-sbd', 'weight-loss', '70 minutos', 5, NULL),
(81, 51, NULL, 33, '2025-08-02 21:53:07', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation (IDF), Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes (SBD) Diretrizes - https://www.diabetes.org.br/publico/diretrizes-sbd', 'weight-loss', '70 minutos', 5, NULL),
(82, 51, NULL, 33, '2025-08-02 21:53:09', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation (IDF), Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines.html\n- Sociedade Brasileira de Diabetes (SBD) Diretrizes - https://www.diabetes.org.br/publico/diretrizes-sbd', 'weight-loss', '70 minutos', 5, NULL),
(83, 51, NULL, 33, '2025-08-02 21:57:49', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '75 minutos', 5, NULL),
(84, 51, NULL, 33, '2025-08-02 21:58:11', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '75 minutos', 5, NULL),
(85, 66, 49, 42, '2025-08-03 19:15:28', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'hypertrophy', '90 minutos', 5, NULL),
(86, 66, 49, 42, '2025-08-03 19:17:08', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'hypertrophy', '90 minutos', 5, NULL),
(87, 68, NULL, 44, '2025-08-03 21:23:24', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '75 minutos', 5, NULL),
(88, 70, 15, 45, '2025-08-04 00:35:00', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'hypertrophy', '75 minutos', 5, NULL),
(89, 63, 15, 40, '2025-08-04 01:30:15', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'weight-loss', '75 minutos', 5, NULL),
(90, 71, 15, 46, '2025-08-05 12:00:57', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. IDF Diabetes Atlas, 10th Edition - https://diabetesatlas.org/', 'weight-loss', '60 minutos', 5, NULL),
(91, 75, 15, 47, '2025-08-06 18:35:22', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'hypertrophy', '80 minutos', 5, NULL),
(92, 75, 15, 47, '2025-08-06 18:44:14', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Diabetes Atlas - https://diabetesatlas.org/', 'hypertrophy', '80 minutos', 5, NULL),
(93, 75, 15, 47, '2025-08-06 18:45:20', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Diabetes Atlas - https://diabetesatlas.org/', 'hypertrophy', '80 minutos', 5, NULL),
(94, 30, 15, 17, '2025-08-06 19:25:09', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'aerobic-resistance', '75 minutos', 5, NULL),
(95, 30, 15, 17, '2025-08-06 19:26:57', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'aerobic-resistance', '75 minutos', 5, NULL),
(96, 30, 15, 17, '2025-08-06 19:43:06', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation (IDF) - https://idf.org\n- Sociedade Brasileira de Diabetes (SBD) - https://www.diabetes.org.br', 'aerobic-resistance', '75 minutos', 5, NULL),
(97, 76, 15, 48, '2025-08-08 17:50:53', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'hypertrophy', '80 minutos', 5, NULL),
(98, 77, 15, 49, '2025-08-10 20:22:48', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'hypertrophy', '75 minutos', 5, NULL),
(99, 81, 15, 53, '2025-08-14 01:38:43', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'hypertrophy', '75 minutos', 5, NULL),
(100, 82, 15, 54, '2025-08-14 01:46:28', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'speed', '75 minutos', 5, NULL),
(101, 82, 15, 54, '2025-08-14 01:50:20', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Global Guidelines for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html\n- Sociedade Brasileira de Diabetes. Diretrizes para o Tratamento do Diabetes Mellitus Tipo 2 - https://www.diabetes.org.br/profissionais/images/Diretrizes/diretrizes-sbd-2019-2020.pdf', 'speed', '70 minutos', 5, NULL),
(102, 82, 15, 54, '2025-08-14 02:04:19', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'speed', '75 minutos', 5, NULL),
(103, 82, 15, 54, '2025-08-14 02:09:16', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'aerobic-resistance', '75 minutos', 5, NULL),
(104, 79, 15, 51, '2025-08-14 02:25:24', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1', 'aerobic-resistance', '70 minutos', 5, NULL),
(105, 80, 15, 52, '2025-08-16 02:34:42', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines/136-idf-clinical-practice-recommendations.html', 'aerobic-resistance', '80 minutos', 5, NULL),
(106, 47, 15, 30, '2025-11-03 20:26:30', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. IDF Diabetes Atlas, 10th Edition - https://diabetesatlas.org/\n- Sociedade Brasileira de Diabetes. Diretrizes da SBD 2022-2023 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2022-2023.pdf', 'aerobic-resistance', '45 minutos', 5, NULL),
(107, 47, 15, 30, '2025-11-03 20:26:33', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. IDF Diabetes Atlas, 10th Edition - https://diabetesatlas.org/\n- Sociedade Brasileira de Diabetes. Diretrizes da SBD 2022-2023 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2022-2023.pdf', 'aerobic-resistance', '45 minutos', 5, NULL),
(108, 47, 15, 30, '2025-11-03 20:26:34', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. IDF Diabetes Atlas, 10th Edition - https://diabetesatlas.org/\n- Sociedade Brasileira de Diabetes. Diretrizes da SBD 2022-2023 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2022-2023.pdf', 'aerobic-resistance', '45 minutos', 5, NULL),
(109, 84, 15, 55, '2025-11-05 03:43:58', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html\n- Sociedade Brasileira de Diabetes. Diretrizes da SBD 2023-2024 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2023-2024.pdf\n- PubMed - National Center for Biotechnology Information - https://pubmed.ncbi.nlm.nih.gov/', 'aerobic-resistance', '90 minutos', 5, NULL),
(110, 84, 15, 55, '2025-11-05 03:43:59', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html\n- Sociedade Brasileira de Diabetes. Diretrizes da SBD 2023-2024 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2023-2024.pdf\n- PubMed - National Center for Biotechnology Information - https://pubmed.ncbi.nlm.nih.gov/', 'aerobic-resistance', '90 minutos', 5, NULL),
(111, 84, 15, 55, '2025-11-05 03:44:08', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html\n- Sociedade Brasileira de Diabetes. Diretrizes da SBD 2023-2024 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2023-2024.pdf\n- PubMed - National Center for Biotechnology Information - https://pubmed.ncbi.nlm.nih.gov/', 'aerobic-resistance', '90 minutos', 5, NULL);
INSERT INTO `planos_treino_gerados` (`id`, `usuario_id`, `profissional_id`, `anamnese_id`, `data_criacao_plano`, `bibliografia_plano`, `foco_primario`, `duracao_treino_geral`, `dias_plano`, `equipamento_geral`) VALUES
(112, 41, 15, 27, '2025-11-05 22:12:34', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html\n- Sociedade Brasileira de Diabetes. Diretrizes da SBD 2023-2024 - https://www.diabetes.org.br/profissionais/images/pdf/diretrizes-sbd-2023-2024.pdf\n- PubMed - National Center for Biotechnology Information - https://pubmed.ncbi.nlm.nih.gov/', 'weight-loss', '75 minutos', 5, NULL),
(113, 41, 15, 27, '2025-11-05 22:12:52', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Global Guideline for Type 2 Diabetes - https://www.idf.org/e-library/guidelines/79-global-guideline-for-type-2-diabetes.html\n- Sociedade Brasileira de Diabetes. Diretrizes da SBD 2023-2024 - https://www.diabetes.org.br/profissionais/images/pdf/diretrizes-sbd-2023-2024.pdf\n- PubMed - National Center for Biotechnology Information - https://pubmed.ncbi.nlm.nih.gov/', 'weight-loss', '75 minutos', 5, NULL),
(114, 85, 15, 56, '2025-11-11 02:34:18', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. Clinical Practice Recommendations - https://www.idf.org/e-library/guidelines/81-idf-clinical-practice-recommendations.html\n- Sociedade Brasileira de Diabetes. Diretrizes SBD 2023-2024 - https://www.diabetes.org.br/profissionais/images/diretrizes/diretrizes-sbd-2023-2024.pdf\n- PubMed - https://pubmed.ncbi.nlm.nih.gov/', 'weight-loss', '75 minutos', 5, NULL),
(115, 40, 15, 26, '2025-11-11 13:40:49', '==Bibliografia Recomendada==\n- ACSM Guidelines for Exercise Testing and Prescription, 11th Edition - https://www.acsm.org/read-research/books/acsms-guidelines-for-exercise-testing-and-prescription\n- American Diabetes Association. Standards of Medical Care in Diabetes—2024 - https://diabetesjournals.org/care/issue/47/Supplement_1\n- International Diabetes Federation. IDF Diabetes Atlas, 10th edition - https://diabetesatlas.org/\n- Sociedade Brasileira de Diabetes. Diretrizes da Sociedade Brasileira de Diabetes 2022-2023 - https://www.diabetes.org.br/profissionais/images/DIRETRIZES-SBD-2022-2023.pdf', 'weight-loss', '75 minutos', 5, NULL);

--
-- Restrições para tabelas despejadas
--

--
-- Restrições para tabelas `planos_treino_gerados`
--
ALTER TABLE `planos_treino_gerados`
  ADD CONSTRAINT `fk_planos_anamnese` FOREIGN KEY (`anamnese_id`) REFERENCES `anamneses` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_planos_profissional` FOREIGN KEY (`profissional_id`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_planos_usuario` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
